apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJMVzRnY0c5cWIzTnBiVHBuYUhCZldUaHdSRVJKWlVGcWFHcGFaekpKTkZOTlJWVnFPVTg0YUV4U2VtSjZNa2cwUW5SdUlBMEsiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
